### ISSUE TITLE
Blechnum rupestre (Kaulf. ex Link) Christenh. x Blechnum medium (R.Br.) Christenh. returns error in ALA

### ISSUE THREAD

**Issue by TaniaGLaity** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#12]
Blechnum_rupestre_x_Blechnum_medium appears on the taxonomic backbone in ALA but when the link to the species page / records for this species is clicked it returns an error. It is a legitimate taxon according to APNI

**Comment by charvolant** [comment]
Identifier in combined taxonomy is https://id.biodiversity.org.au/https://id.biodiversity.org.au/name/apni/51405246

This is unfindable in the BIE because the rewriting of https://bie.ala.org.au/species/https://id.biodiversity.org.au/https://id.biodiversity.org.au/name/apni/51405246 results in an identifier of `https://id.biodiversity.org.au/https:/id.biodiversity.org.au/name/apni/51405246` (note single / after second https) https://bie-ws.ala.org.au/ws/species?id=https://id.biodiversity.org.au/https://id.biodiversity.org.au/name/apni/51405246 will work correctly but that is not how things are done.

The error is in the source APC download.

**Comment by charvolant** [comment]
Fixed in https://github.com/AtlasOfLivingAustralia/name-preprocessing/pull/6 code removes stuttering, rather than manually editing.

**Comment by CamSlatyer** [comment]
This has correctly assigned from APNI, HOWEVER, Blechnum rupestre (Kaulf. ex Link) Christenh. x Blechnum medium (R.Br.) Christenh. is an APC approved species!!!! https://biodiversity.org.au/nsl/services/search/names?product=APNI&tree.id=&name=Blechnum+rupestre+%28Kaulf.+ex+Link%29+Christenh.+x+Blechnum+medium+%28R.Br.%29+Christenh.&inc._scientific=&inc.scientific=on&inc._cultivar=&inc._other=&max=100&display=apni&search=true
