### ISSUE TITLE
Duplicate species pages Eucalyptus Cattai

### ISSUE THREAD

**Issue by TaniaGLaity** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#36]
Eucalyptus sp. Cattai (listed in NSW) and Eucalyptus sp. Cattai (Gregson s.n. 28 Aug 1954) NSW Herbarium (listed under EPBC and the APC Accepted Name) are both linked to Eucalyptus Cattai on the taxonomic backbone but don't appear in the tree under Eucalyptus.  they need to be synonymised

**Comment by Sherrin-ALA** [comment]
These species aren't being detected as synonymous because APC is supplying Eucalyptus sp. Cattai (Gregson s.n. 28 Aug 1954) as the scientific name, with NSW Herbarium as the author.

As to why neither of these species (and a few similar species) aren't appearing in tree under Eucalyptus requires further investigation.

**Comment by CamSlatyer** [comment]
Correct in tactical taxonomy
