### ISSUE TITLE
Bettongia lesueur subspecies duplicated

### ISSUE THREAD

**Issue by TaniaGLaity** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#46]
Bettongia lesueur Barrow and Boodie Island subpecies have 3 separate entries on the taxonomic backbone. This subspecies is listed in both WA and on EPBC Act but the status is showing on separate entries

**Comment by charvolant** [comment]
See #4 for issue on attaching geography to species names.

* ALA_DR2201_4202 https://lists.ala.org.au/speciesListItem/list/dr2201?q=Bettongia+lesueur+subsp.+%28Barrow+and+Boodie+Islands%29 gives the name as `Bettongia lesueur subsp. (Barrow and Boodie Islands)`
* ALA_DR656_242 https://lists.ala.org.au/speciesListItem/list/dr656?q=Bettongia+lesueur+Barrow+and+Boodie+Islands+subspecies gives the name as `Bettongia lesueur Barrow and Boodie Islands subspecies`

Rather than attempt to identify similarities, if we have these, correct the list entries to match.

**Comment by Sherrin-ALA** [comment]
Conservation list issue - similar to issue #21 - and to be resolved in a similar matter. Whatever that turns out to be.

**Comment by CamSlatyer** [comment]
Corrected in tactical taxonomy
